name: Publish image to dockerhub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # - name: Build the Docker image
    #   run: |
    #     docker build . -t abaloit/remoteconnection:latest
    - name: Set up Docker Buildx
      run: |
        docker buildx create --use
    - name: build & push publish
      run: |
        docker login -u abaloit -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker buildx build . --platform linux/arm64,linux/amd64 -t abaloit/remoteconnection:latest --push

